on:
  #push:
    #branches: main
  #pull_request:
    #branches: main
  workflow_dispatch:

name: test

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          update-rtools: true
      - name: Install system dependencies ubuntu
        run: |
          sudo apt install -y libcurl4-openssl-dev libgdal-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Install system dependencies mac
        run: |
          brew install gdal
        if: matrix.os == 'macos-latest'
      - name: Install Packages
        run: |
          install.packages('packrat')
          packrat::restore()
        shell: Rscript {0}
      - name: Test
        run: |
          .libPaths(packrat::lib_dir())
          shiny::runTests()
        shell: Rscript {0}